name: Create release

on:
#    milestone:
#        types: [closed]
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  prepare-version:  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: Create version file
      run: cat pom.xml |grep version| head -1|sed -e 's/<[^>]*>//g'|xargs > sh/current.version
    - name: Commit report
      run: |
        git config --global user.name 'Notepack Bot'
        git config --global user.email 'bot@notepackapp.com'
        git commit -am "Automated report"
        git push        
  
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Version
      run: APP_VERSION=`cat sh/current.version`
    - name: Build with Maven
      run: java -version ; mvn -X clean install resources:resources compiler:compile javafx:jlink --file pom.xml
    - name: Create jpackage
      run: jpackage -n notepack --runtime-image target/notepack/ -m notepack/notepack.Main --app-version $APP_VERSION --icon gfx/logo_64.png
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: release-linux.zip
        path: target/notepack


  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - shell: bash
      run: |
         APP_VERSION=`cat sh/current.version`          
    - name: Build with Maven
      run: java -version ; mvn -X clean install resources:resources compiler:compile javafx:jlink --file pom.xml
    - name: Create jpackage
      run: jpackage -n notepack --runtime-image target/notepack/ -m notepack/notepack.Main --app-version $APP_VERSION --icon gfx/logo_64.ico   
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: release-windows.zip
        path: target/notepack

